# Generated by Django 4.2.5 on 2023-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
