# Generated by Django 4.2.5 on 2023-09-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='namess',
        ),
    ]
