# Generated by Django 4.2.5 on 2023-09-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_rename_namess_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='names',
        ),
    ]
