# Generated by Django 4.2.5 on 2023-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='good shoes', max_length=200),
        ),
    ]
