# Generated by Django 4.2.5 on 2023-09-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='is_avilable',
            new_name='is_available',
        ),
    ]
