# Generated by Django 4.2.5 on 2023-09-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_is_avilable_color_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
