# Generated by Django 4.2.5 on 2023-09-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='product',
            new_name='productss',
        ),
    ]
