# Generated by Django 4.2.5 on 2023-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0005_alter_variant_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
