# Generated by Django 4.2.5 on 2023-11-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_created_at_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
