# Generated by Django 4.2.5 on 2023-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emails',
            field=models.EmailField(blank=True, max_length=20),
        ),
    ]
