# Generated by Django 4.2.5 on 2023-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
