# Generated by Django 4.2.5 on 2023-09-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Variant',
            new_name='variant',
        ),
    ]
