# Generated by Django 4.2.5 on 2023-11-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderss',
        ),
    ]
